### ISSUE TITLE
不存在copy模块

### ISSUE THREAD

**Issue by ChaoQiezi** [scouthe/Remote-sensing-CNN-land-classify#1]
当我执行至features = imageChipsFromFile(feature_file, x_size=3, y_size=3) 进行特征矩阵的获取时，发现报错：
Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-8721fb789954>", line 10, in <cell line: 10>
    features = imageChipsFromFile(feature_file, x_size=3, y_size=3)
  File "D:\Python310\lib\site-packages\pyrsgis\ml\__init__.py", line 207, in imageChipsFromFile
    return(imageChipsFromArray(data_arr, y_size=y_size, x_size=x_size))
  File "D:\Python310\lib\site-packages\pyrsgis\ml\__init__.py", line 134, in imageChipsFromArray
    data_array = copy.copy(data_array)
NameError: name 'copy' is not defined
这是否是由于pyrsgis版本的更新问题导致的？能否告知我您的版本信息？或者有其它解决方案，谢谢。

**Comment by ChaoQiezi** [comment]
谢谢作者，已经解决了，是由于pyrsgis模块更新问题导致了该错误，现已修复。只需要将pyrsgis\ml\__init__.py文件中第134行中的copy.copy更改为deepcopy即可。下一个版本应该会修复该问题。
